os:
- linux
- osx
- windows
language: c
env:
- SBCL_VERSION="2.0.3" CSOUND_VERSION="6.14.0"
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/csound"
  - "$HOME/sbcl"
  - "$HOME/quicklisp"
  - "$HOME/.cache/common-lisp"
  - "$HOME/AppData/Local/cache/common-lisp"
install:
- SOURCE_DIR=$(pwd)
- cd ~
- if [ "$TRAVIS_OS_NAME" = "windows" -a ! -f "$HOME/sbcl/bin/sbcl" ]; then SBCL_WINDOWS="http://prdownloads.sourceforge.net/sbcl/sbcl-1.4.14-x86-64-windows-binary.msi";
  wget $SBCL_WINDOWS -O sbcl.msi; choco install lessmsi make; lessmsi x sbcl.msi $(cygpath
  -w "`pwd`/sbcl_ex/"); mv "sbcl_ex/SourceDir/PFiles/Steel Bank Common Lisp/1.4.14"
  sbcl_bin; export SBCL_HOME="`pwd`/sbcl_bin"; export PATH="`pwd`/sbcl_bin:${PATH}";
  fi
- if [ "$TRAVIS_OS_NAME" = "osx"   -a ! -f "$HOME/sbcl/bin/sbcl" ]; then HOMEBREW_NO_AUTO_UPDATE=1
  brew install sbcl; fi
- if [ "$TRAVIS_OS_NAME" = "linux" -a ! -f "$HOME/sbcl/bin/sbcl" ]; then sudo apt
  update; sudo apt install sbcl; fi
- if [ ! -f "$HOME/sbcl/bin/sbcl" ]; then SBCL_SOURCE="http://downloads.sourceforge.net/project/sbcl/sbcl/$SBCL_VERSION/sbcl-$SBCL_VERSION-source.tar.bz2";
  wget $SBCL_SOURCE -O sbcl.tar.bz2; tar -xf sbcl.tar.bz2; cd "sbcl-$SBCL_VERSION";
  sh make.sh --fancy; unset SBCL_HOME; INSTALL_ROOT=~/sbcl ./install.sh; cd ~; fi
- export SBCL_HOME="$HOME/sbcl/lib/sbcl"
- export PATH="$HOME/sbcl/bin:${PATH}"
- if [ ! -f "$HOME/quicklisp/setup.lisp" ]; then wget https://beta.quicklisp.org/quicklisp.lisp;
  sbcl --disable-debugger --eval "(load \"quicklisp.lisp\")" --eval "(quicklisp-quickstart:install)"
  --eval "(ql-util:without-prompting (ql:add-to-init-file))" --eval "(ql:update-all-dists)"
  --eval "(sb-ext:exit)"; else sbcl --disable-debugger --eval "(load \"quicklisp/setup.lisp\")"
  --eval "(ql-util:without-prompting (ql:add-to-init-file))" --eval "(sb-ext:exit)";
  rm -rf ~/quicklisp/local-projects; mkdir ~/quicklisp/local-projects; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install csound; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt
  update; sudo apt install csound libcsound64-6.0; fi
- |
  if [ "$TRAVIS_OS_NAME" = "windows" -a ! -f "$HOME/csound/csound.zip" ]; then
    mkdir -p csound/
    cd csound/
    wget -O csound.zip https://github.com/csound/csound/releases/download/${CSOUND_VERSION}/Csound${CSOUND_VERSION}-Windows_x64-binaries.zip
    7z x csound.zip
    cd ~
  fi
  if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    cp -v $HOME/csound/*.dll C:/windows/system32/
  fi
- mv $SOURCE_DIR ~/quicklisp/local-projects
script:
- sbcl --disable-debugger --eval "(ql:update-all-dists)" --eval "(sb-ext:exit)"
- sbcl --disable-debugger --eval "(ql:quickload :csound)" --eval "(sb-ext:exit)"
